service:
  name: AuditToolBackend

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  timeout: 12
  environment:
    NODE_ENV: ${env:NODE_ENV}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}

functions:
  product:
    handler: src/startup.enrtyPoint
    events:
      - http:
          method: get
          # get products by user id
          path: product/user/{id}
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: get
          path: product/{id}
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: get
          path: product/{id}/phases
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: get
          # return the product by product_phase_id
          path: product/productPhases/{id}
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: get
          path: productPhase/{id}/knowledgeAreas
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: get
          path: knowledgeArea/{id}/questions
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: get
          path: product/{id}/questions/{qid}/evidence
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: post
          path: question/{id}/evidence
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: post
          path: authTrigger/user
      - http:
          method: put
          path: question/{id}/evidence/{eid}
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: get
          path: product/{id}/productPhase
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: get
          path: product/{id}/question/{qid}/page/{pid}
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: get
          path: user/email/{id}
      - http:
          method: get
          path: user/product/{id}
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: get
          path: evidence/{id}
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: get
          path: product/{id}/question/{qid}/evidence/date/{did}
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: post
          path: admin/userProducts
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: post
          path: admin/product
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: get
          path: admin/products
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: get
          path: admin/users
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
      - http:
          method: get
          path: admin/organizations
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:ARN}
  auth-token-trigger:
    handler: src/functions/auth-token-trigger.authToken
