service:
  name: AuditToolBackend
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${env:NODE_ENV}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}

functions:
  product:
    handler: src/products/handler.product
    events:
      - http:
          method: get
          path: products
          cors: true
      - http:
          method: get
          path: products/{id}
          cors: true
      - http:
          method: get
          path: products/{id}/phases
          cors: true
      - http:
          method: get
          path: products/productPhases/{id}
          cors: true
  knowledgeArea:
    handler: src/knowledge-areas/handler.knowledgeArea
    events:
      - http:
          method: get
          path: productPhase/{id}/knowledgeAreas
          cors: true
